# Generated by Django 5.2.4 on 2025-09-01 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='registrations_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
