# Generated by Django 5.2.4 on 2025-09-01 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_event_registrations_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='category',
            field=models.CharField(choices=[('music', 'Music'), ('sports', 'Sports'), ('tech', 'Technology'), ('art', 'Art'), ('education', 'Education'), ('other', 'Other'), ('health', 'Health & Wellness'), ('food', 'Food & Drink')], default='other', max_length=50),
        ),
    ]
