# Generated by Django 5.2.4 on 2025-09-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_booking_payment_status_alter_event_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='canceled_tickets',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
